// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADOaORZRmrOe-91__C5hxbErKonut0E6M',
    appId: '1:1092525721003:web:fef31fb2551c124930feee',
    messagingSenderId: '1092525721003',
    projectId: 'grenadesapp-71747',
    authDomain: 'grenadesapp-71747.firebaseapp.com',
    storageBucket: 'grenadesapp-71747.firebasestorage.app',
    measurementId: 'G-18LD1XTBC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAP3OdPxL_L0jMe7IiHQH760CNmTbQJvM',
    appId: '1:1092525721003:android:2df21d045b12ebf530feee',
    messagingSenderId: '1092525721003',
    projectId: 'grenadesapp-71747',
    storageBucket: 'grenadesapp-71747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-7qAjHVvpaBeddzv9sQiewduNsdzRQMQ',
    appId: '1:1092525721003:ios:9fe5ac0be48f5d7830feee',
    messagingSenderId: '1092525721003',
    projectId: 'grenadesapp-71747',
    storageBucket: 'grenadesapp-71747.firebasestorage.app',
    iosBundleId: 'com.example.grenadesapp',
  );
}
